### ISSUE TITLE
PDF2HTMLEX issue

### ISSUE THREAD

**Issue by xubairp** [3Alan/DocsMind#14]
**Describe the bug**
Running the following command run into error :

`alias pdf2htmlex='docker run -ti --rm -v "`pwd`":/pdf -w /pdf pdf2htmlex/pdf2htmlex:0.18.8.rc2-master-20200820-alpine-3.12.0-x86_64' `

```
alias : This command cannot find a matching alias because an alias with the name 'pdf2htmlEX=docker run -ti --rm -v "`pwd`":/pdf -w /pdf 
pdf2htmlex/pdf2htmlex:0.18.8.rc2-master-20200820-alpine-3.12.0-x86_64' does not exist.
At line:1 char:1
+ alias pdf2htmlEX='docker run -ti --rm -v "`pwd`":/pdf -w /pdf pdf2htm ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (pdf2htmlEX=dock...e-3.12.0-x86_64:String) [Get-Alias], ItemNotFoundException
    + FullyQualifiedErrorId : ItemNotFoundException,Microsoft.PowerShell.Commands.GetAliasCommand
```

**Comment by 3Alan** [comment]
Hello, pdf2htmlex is just my experimental branch for processing PDFs. Just now I updated my latest PDF (without using pdf2htmlex).

**Comment by xubairp** [comment]
Hi Alan, 
 So if i understand it correctly, its optional to install/use the pdf2htmlex and we can use the app without it ?

**Comment by 3Alan** [comment]
Yes, only the code in the main branch is usable. The code in other branches is experimental and under development, so you should not use my other branches.

**Comment by xubairp** [comment]
ok great.

thanks
