### ISSUE TITLE
File upload fail. undefined. 

### ISSUE THREAD

**Issue by thunderwilson** [3Alan/DocsMind#16]
**Describe the bug**
Cannot upload PDF documents. 

**Provide logs**
Please provide the log located at `logs/app.log` and the client error (browser console) so that I can better understand the issue.
<img width="994" alt="image" src="https://user-images.githubusercontent.com/9668112/236810258-b14de886-6100-4f33-ac2a-6b07b3ba9549.png">

**To Reproduce**
Follow instructions in README.md, hosting on github codespace, and gitpod. 

**Expected behavior**
PDF would upload and be indexed. 

**Screenshots**
<img width="593" alt="image" src="https://user-images.githubusercontent.com/9668112/236810792-b3503e4a-6052-40fe-bacd-1f1fc54be810.png">

**Comment by 3Alan** [comment]
Can you access your backend service through 127.0.0.1:8080? It seems that your backend service is not running.

**Comment by thunderwilson** [comment]
<img width="1177" alt="image" src="https://user-images.githubusercontent.com/9668112/236815907-bdeb1537-d6d3-4221-9277-04242b8b683b.png">

**Comment by thunderwilson** [comment]
I thought it might have something to do with the fact the the github codespaces url is unique, so I tried updating .env 


VITE_SERVICES_URL="https://8080-thunderwilson-docsmind-844wuco251l.ws-us96b.gitpod.io/"

Still no luck.

Do you perhaps have instructions for deploying to vercel or alternative?

**Comment by 3Alan** [comment]
You are right. You can try replacing 127.0.0.1 with 0.0.0.0 in the code and rebuild it.
Also, we cannot deploy to Vercel as their support for Python projects is not very good. You can deploy to any cloud service provider that supports Docker.

**Comment by thunderwilson** [comment]
Could you provide some guidance on deploying on railway?

**Comment by 3Alan** [comment]
Duplicate https://github.com/3Alan/DocsMind/discussions/17#discussion-5176667
