### ISSUE TITLE
This error occurs when the front-end uploads the file

### ISSUE THREAD

**Issue by chappyhome** [3Alan/DocsMind#21]
**Describe the bug**
![image](https://github.com/3Alan/DocsMind/assets/1982081/edb3c7e1-54d0-483f-aa4b-03d94591b88e)

**Provide logs**
Please provide the log located at `logs/app.log` and the client error (browser console) so that I can better understand the issue.

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by 3Alan** [comment]
Duplicate https://github.com/3Alan/DocsMind/issues/16
